/**
 * Aggregat der Contract-Schicht (Roadmap-Etappe 1).
 *
 * Versionierte, frontend-unabhängige Verträge (DTOs, Events, Enums,
 * Validatoren) für Chat, Streaming, Tools und Token-Usage. Single Source of
 * Truth für Main (require) und Renderer (generiertes ESM-Bundle).
 *
 * Das module.exports ist bewusst ein flaches Objekt-Literal, damit esbuild
 * beim CJS→ESM-Bundling für den Renderer benannte Exporte ableiten kann.
 */
'use strict';

const {
  CONTRACT_VERSION,
  CHAT_ERROR_CODES,
  CHAT_PHASES,
  TOOL_LINE_PHASES,
  CHAT_PROGRESS_TYPES,
  APP_LOCALES,
  SKILL_SUGGESTION_MODES,
  DEFAULT_SKILL_SUGGESTION_MODE,
  isSkillSuggestionMode,
  PRESET_DETAIL_STYLES,
  PRESET_FIELD_TYPES,
  WORKSPACE_PROGRESS_EVENTS,
  PERMISSION_PROGRESS_EVENTS,
} = require('./enums');
const {
  clampMaxToolRounds,
  clampSidebarWidth,
  clampChatPanelWidth,
  clampHistoryCharLimit,
  isAppLocale,
  createSettingsOk,
  createSettingsError,
  createListModelsResult,
  normalizePresetWire,
  presetIdentityKey,
  normalizeProviderPatch,
  normalizeUiPrefs,
  normalizeUiPrefsPatch,
  normalizeListModelsRequest,
  formatConnectionDetail,
  formatPresetSublabel,
  formatPresetSublabelFromView,
  formatPresetOptionSuffixFromView,
  buildPresetFieldViews,
  buildProviderFormView,
} = require('./settings');
const {
  SKILL_SOURCES,
  SKILL_SOURCE_ORDER,
  SKILL_SOURCE_LABEL_KEYS,
  SKILL_STATUS,
  isValidSkillName,
  normalizeActiveSkills,
  normalizeSkillSummary,
  normalizeSkillCatalog,
} = require('./skills');
const {
  findSkillQuery,
  extractInvokedSkillNames,
  filterSkillCandidates,
  applySkillInvocation,
} = require('./skill-invocation');
const {
  createSkillSuggester,
  SUGGESTION_THRESHOLD,
} = require('./skill-suggestion');
const { toUsageNumber, createEmptyUsage, normalizeUsage, coerceUsage, mergeUsage } = require('./usage');
const {
  CONTEXT_BREAKDOWN_VERSION,
  CONTEXT_PART_GROUPS,
  CONTEXT_PART_GROUP_ORDER,
  CONTEXT_PART_GROUP_LABEL_KEYS,
  CONTEXT_CONTENT_KINDS,
  CHARS_PER_TOKEN,
  estimateTokensFromChars,
  createContextPart,
  createContextBreakdown,
  normalizeContextBreakdown,
  groupContextParts,
} = require('./context-breakdown');
const { endpointHost, isLocalEndpoint } = require('./provider-endpoint');
const {
  TOOL_CATEGORIES,
  TOOL_CATEGORY_BY_TOOL,
  toolCategory,
  toolCategoryForEntry,
} = require('./tool-categories');
const {
  CHAT_TITLE_MAX_LENGTH,
  inferChatTitle,
  inferChatTitleText,
  isDerivedChatTitle,
  isLegacyFallbackChatTitle,
  resolveChatTitle,
  sanitizeChatTitle,
  createChatResult,
  createCancelledChatResult,
  createChatErrorResult,
  createDeltaEvent,
  createToolLineEvent,
  createPhaseEvent,
  createReasoningEvent,
  createWorkspaceFileWrittenEvent,
  createPermissionProgressEvent,
  isChatErrorCode,
  isChatPhase,
  isToolLinePhase,
} = require('./chat');
const {
  createWorkspaceTreeChangedEvent,
  MAX_TREE_CHANGED_DIRECTORIES,
} = require('./workspace-tree');
const {
  MAX_WORKSPACE_IMAGE_BYTES,
  WORKSPACE_IMAGE_ERRORS,
  WORKSPACE_IMAGE_MIME_TYPES,
  WORKSPACE_IMAGE_SNIFF_BYTES,
  sniffImageMime,
  decodeWorkspaceImageSource,
  isWorkspaceImageSource,
  isWindowsDrivePath,
  createWorkspaceImageResult,
  createWorkspaceImageError,
  workspaceImageErrorMessageKey,
  workspaceImageDataUrl,
} = require('./workspace-image');
const {
  MAX_VOICE_RECORDING_MS,
  MAX_VOICE_RECORDING_BYTES,
  VOICE_STOP_WARNING_MS,
  MAX_TRANSCRIPTION_UPLOAD_BYTES,
  checkTranscriptionPayload,
} = require('./voice');
const {
  ATTACHMENT_KINDS,
  MAX_IMAGE_ATTACHMENT_BYTES,
  MAX_IMAGES_PER_MESSAGE,
  MAX_IMAGE_EDGE_PX,
  IMAGE_ATTACHMENT_MEDIA_TYPES,
  IMAGE_ATTACHMENT_CHAR_COST,
  isImageMediaType,
  normalizeImageAttachment,
  normalizeAttachments,
  imageAttachmentsOf,
  attachmentsCharCost,
  toDataUrl,
} = require('./attachments');
const {
  TOOL_PERMISSIONS_CONTRACT_VERSION,
  TOOL_RISK_CLASSES,
  TOOL_RISK_CLASS_ORDER,
  TOOL_PERMISSION_MODES,
  TOOL_PERMISSION_MODE_LABEL_KEYS,
  TOOL_RISK_CLASS_LABEL_KEYS,
  DEFAULT_TOOL_PERMISSION_MODE,
  POLICY_DECISIONS,
  APPROVAL_RESPONSES,
  PERMISSION_DECISION_SOURCES,
  PERMISSION_DENIAL_REASONS,
  PERMISSION_DENIED_MESSAGE_KEYS,
  PERMISSION_DENIED_TOOL_RESULT_MESSAGES,
  TOOL_EXECUTION_STATUSES,
  PERMISSION_RULE_EFFECTS,
  PERMISSION_RULE_SCOPES,
  SESSION_GRANTABLE_CLASSES,
  PERSISTENT_ALLOW_CLASSES,
  COMMAND_RULE_TOOL,
  COMMAND_RULE_UNAVAILABLE_REASONS,
  SENSITIVE_CONTENT_REDACTED_TEXT,
  isToolRiskClass,
  isToolPermissionMode,
  normalizeToolPermissionMode,
  normalizeApprovalResponse,
  normalizeRiskClasses,
  normalizeRulePathPattern,
  normalizePermissionRule,
  normalizePermissionRules,
  normalizeRememberableCommand,
  normalizeCommandCwd,
  isCommandRule,
  normalizeSensitivePathPatterns,
  createPermissionDeniedToolResult,
  parsePermissionDeniedToolResult,
  createToolApprovalRequestDto,
  isToolApprovalRequestDto,
  normalizeToolApprovalResponse,
  createPermissionAuditEntry,
} = require('./tool-permissions');

const {
  MCP_CONTRACT_VERSION,
  MCP_PROTOCOL_VERSION,
  MCP_TRANSPORTS,
  MCP_TRANSPORT_LIST,
  MCP_CONNECTION_STATES,
  MCP_LIMITS,
  MCP_TIMEOUTS,
  isValidMcpServerId,
  isMcpTransport,
  isMcpConnectionState,
  validateMcpServerConfig,
  normalizeMcpServerConfig,
  normalizeMcpToolCatalogEntry,
  normalizeMcpToolCatalog,
  createMcpConnectionStatus,
} = require('./mcp');
const {
  MCP_IMPORT_MAX_SERVERS,
  parseMcpServersBlock,
  toMcpServerInput,
} = require('./mcp-import');
const {
  MEMORY_SCOPES,
  MEMORY_SCOPE_ORDER,
  MEMORY_SCOPE_LABEL_KEYS,
  MEMORY_SCOPE_PROMPT_LABELS,
  MEMORY_SCOPE_PATHS,
  MEMORY_ORIGINS,
  MAX_MEMORY_CHARS,
  MAX_MEMORY_ENTRY_CHARS,
  isMemoryScope,
  parseMemoryEntries,
} = require('./memory');
const {
  PROGRAM_ALLOWANCE_LIMITS,
  PROGRAM_ALLOWANCE_SKIP_REASONS,
  programName,
  normalizeAllowancePath,
  normalizeProgramAllowance,
  normalizeProgramAllowances,
  grantsSomething,
  parseDomainInput,
  isNarrowing,
} = require('./program-allowances');

const { createMessage, isMessage } = require('./message');

module.exports = {
  createMessage,
  isMessage,
  CONTRACT_VERSION,
  CHAT_ERROR_CODES,
  CHAT_PHASES,
  TOOL_LINE_PHASES,
  CHAT_PROGRESS_TYPES,
  WORKSPACE_PROGRESS_EVENTS,
  PERMISSION_PROGRESS_EVENTS,
  APP_LOCALES,
  SKILL_SUGGESTION_MODES,
  DEFAULT_SKILL_SUGGESTION_MODE,
  isSkillSuggestionMode,
  PRESET_DETAIL_STYLES,
  PRESET_FIELD_TYPES,
  clampMaxToolRounds,
  clampSidebarWidth,
  clampChatPanelWidth,
  clampHistoryCharLimit,
  isAppLocale,
  createSettingsOk,
  createSettingsError,
  createListModelsResult,
  normalizePresetWire,
  presetIdentityKey,
  normalizeProviderPatch,
  normalizeUiPrefs,
  normalizeUiPrefsPatch,
  normalizeListModelsRequest,
  formatConnectionDetail,
  formatPresetSublabel,
  formatPresetSublabelFromView,
  formatPresetOptionSuffixFromView,
  buildPresetFieldViews,
  buildProviderFormView,
  SKILL_SOURCES,
  SKILL_SOURCE_ORDER,
  SKILL_SOURCE_LABEL_KEYS,
  SKILL_STATUS,
  isValidSkillName,
  normalizeActiveSkills,
  normalizeSkillSummary,
  normalizeSkillCatalog,
  findSkillQuery,
  extractInvokedSkillNames,
  filterSkillCandidates,
  applySkillInvocation,
  createSkillSuggester,
  SUGGESTION_THRESHOLD,
  toUsageNumber,
  createEmptyUsage,
  normalizeUsage,
  coerceUsage,
  mergeUsage,
  CONTEXT_BREAKDOWN_VERSION,
  CONTEXT_PART_GROUPS,
  CONTEXT_PART_GROUP_ORDER,
  CONTEXT_PART_GROUP_LABEL_KEYS,
  CONTEXT_CONTENT_KINDS,
  CHARS_PER_TOKEN,
  estimateTokensFromChars,
  createContextPart,
  createContextBreakdown,
  normalizeContextBreakdown,
  groupContextParts,
  endpointHost,
  isLocalEndpoint,
  TOOL_CATEGORIES,
  TOOL_CATEGORY_BY_TOOL,
  toolCategory,
  toolCategoryForEntry,
  CHAT_TITLE_MAX_LENGTH,
  inferChatTitle,
  inferChatTitleText,
  isDerivedChatTitle,
  isLegacyFallbackChatTitle,
  resolveChatTitle,
  sanitizeChatTitle,
  createChatResult,
  createCancelledChatResult,
  createChatErrorResult,
  createDeltaEvent,
  createToolLineEvent,
  createPhaseEvent,
  createReasoningEvent,
  createWorkspaceFileWrittenEvent,
  createPermissionProgressEvent,
  isChatErrorCode,
  isChatPhase,
  isToolLinePhase,
  createWorkspaceTreeChangedEvent,
  MAX_TREE_CHANGED_DIRECTORIES,
  MAX_WORKSPACE_IMAGE_BYTES,
  WORKSPACE_IMAGE_ERRORS,
  WORKSPACE_IMAGE_MIME_TYPES,
  WORKSPACE_IMAGE_SNIFF_BYTES,
  sniffImageMime,
  decodeWorkspaceImageSource,
  isWorkspaceImageSource,
  isWindowsDrivePath,
  createWorkspaceImageResult,
  createWorkspaceImageError,
  workspaceImageErrorMessageKey,
  workspaceImageDataUrl,
  ATTACHMENT_KINDS,
  MAX_IMAGE_ATTACHMENT_BYTES,
  MAX_IMAGES_PER_MESSAGE,
  MAX_IMAGE_EDGE_PX,
  IMAGE_ATTACHMENT_MEDIA_TYPES,
  IMAGE_ATTACHMENT_CHAR_COST,
  isImageMediaType,
  normalizeImageAttachment,
  normalizeAttachments,
  imageAttachmentsOf,
  attachmentsCharCost,
  toDataUrl,
  TOOL_PERMISSIONS_CONTRACT_VERSION,
  TOOL_RISK_CLASSES,
  TOOL_RISK_CLASS_ORDER,
  TOOL_PERMISSION_MODES,
  TOOL_PERMISSION_MODE_LABEL_KEYS,
  TOOL_RISK_CLASS_LABEL_KEYS,
  DEFAULT_TOOL_PERMISSION_MODE,
  POLICY_DECISIONS,
  APPROVAL_RESPONSES,
  PERMISSION_DECISION_SOURCES,
  PERMISSION_DENIAL_REASONS,
  PERMISSION_DENIED_MESSAGE_KEYS,
  PERMISSION_DENIED_TOOL_RESULT_MESSAGES,
  TOOL_EXECUTION_STATUSES,
  PERMISSION_RULE_EFFECTS,
  PERMISSION_RULE_SCOPES,
  SESSION_GRANTABLE_CLASSES,
  PERSISTENT_ALLOW_CLASSES,
  COMMAND_RULE_TOOL,
  COMMAND_RULE_UNAVAILABLE_REASONS,
  SENSITIVE_CONTENT_REDACTED_TEXT,
  isToolRiskClass,
  isToolPermissionMode,
  normalizeToolPermissionMode,
  normalizeApprovalResponse,
  normalizeRiskClasses,
  normalizeRulePathPattern,
  normalizePermissionRule,
  normalizePermissionRules,
  normalizeRememberableCommand,
  normalizeCommandCwd,
  isCommandRule,
  normalizeSensitivePathPatterns,
  createPermissionDeniedToolResult,
  parsePermissionDeniedToolResult,
  createToolApprovalRequestDto,
  isToolApprovalRequestDto,
  normalizeToolApprovalResponse,
  createPermissionAuditEntry,
  MCP_CONTRACT_VERSION,
  MCP_PROTOCOL_VERSION,
  MCP_TRANSPORTS,
  MCP_TRANSPORT_LIST,
  MCP_CONNECTION_STATES,
  MCP_LIMITS,
  MCP_TIMEOUTS,
  isValidMcpServerId,
  isMcpTransport,
  isMcpConnectionState,
  validateMcpServerConfig,
  normalizeMcpServerConfig,
  normalizeMcpToolCatalogEntry,
  normalizeMcpToolCatalog,
  createMcpConnectionStatus,
  MCP_IMPORT_MAX_SERVERS,
  parseMcpServersBlock,
  toMcpServerInput,
  MEMORY_SCOPES,
  MEMORY_SCOPE_ORDER,
  MEMORY_SCOPE_LABEL_KEYS,
  MEMORY_SCOPE_PROMPT_LABELS,
  MEMORY_SCOPE_PATHS,
  MEMORY_ORIGINS,
  MAX_MEMORY_CHARS,
  MAX_MEMORY_ENTRY_CHARS,
  isMemoryScope,
  parseMemoryEntries,
  MAX_VOICE_RECORDING_MS,
  MAX_VOICE_RECORDING_BYTES,
  VOICE_STOP_WARNING_MS,
  MAX_TRANSCRIPTION_UPLOAD_BYTES,
  checkTranscriptionPayload,
  PROGRAM_ALLOWANCE_LIMITS,
  PROGRAM_ALLOWANCE_SKIP_REASONS,
  programName,
  normalizeAllowancePath,
  normalizeProgramAllowance,
  normalizeProgramAllowances,
  grantsSomething,
  parseDomainInput,
  isNarrowing,
};
